### ISSUE TITLE
New Release (for Packagist)

### ISSUE THREAD

**Issue by Braunson** [martindilling/Sunny#2]
Can you push out a new release, needed primarily for use in Packagist :+1:

**Comment by martindilling** [comment]
Done, but just fyi, I'm not really supporting or working on this any more. Was made mostly as an exercise :)
I am still here, so I will accept pull requests if needed, but I'm not going to invest time in working on it myself :)

**Comment by Braunson** [comment]
Yep, I understand and appreciate it, it's a handy simple package which we use for sun rise/set as OpenWeatherMap doesn't provided daily sun rise/set but instead only for the current day which is a pain.

Thanks @martindilling

**Comment by martindilling** [comment]
No problem :+1:
Didn't think it was especially useful, but glad it is for someone :)
